version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless
    versions:
    - 2.20.1
    - 2.21.1
    - 2.22.0
    - 2.25.2
    - 2.28.0
    - 2.28.7
    - 2.29.0
    - 2.30.3
    - 2.31.0
    - 2.33.1
    - 2.38.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: fast-xml-parser
    versions:
    - 3.18.0
