name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        # with:
        #   node-version: '22'
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run test
          npm run lint
