name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        # with:
        #   node-version: '14'
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run test
          npm run lint
